sudo: false
language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
# before_script:
# - sbt test:compile
script:
# - sbt test
- for path in */; do
    [ -d "${path}" ] || continue # if not a directory, skip
    dirname="$(basename "${path}")"
    cd "$dirname" || return
    sbt test:compile
    sbt test
    fi
  done
